// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ApplicationStats holds aggregate counts for job applications
 */
export class ApplicationStats {
    "applied": number;
    "failed": number;
    "total": number;

    /** Creates a new ApplicationStats instance. */
    constructor($$source: Partial<ApplicationStats> = {}) {
        if (!("applied" in $$source)) {
            this["applied"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationStats($$parsedSource as Partial<ApplicationStats>);
    }
}

/**
 * JobApplication represents a single job application attempt
 */
export class JobApplication {
    "id": number;
    "profileId": number;
    "jobId": string;
    "title": string;
    "company": string;

    /**
     * "applied" or "failed"
     */
    "status": string;
    "errorMessage": string;
    "appliedAt": time$0.Time;

    /** Creates a new JobApplication instance. */
    constructor($$source: Partial<JobApplication> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = 0;
        }
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("appliedAt" in $$source)) {
            this["appliedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobApplication instance from a string or object.
     */
    static createFrom($$source: any = {}): JobApplication {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobApplication($$parsedSource as Partial<JobApplication>);
    }
}

/**
 * LinkedInProfile represents a user's LinkedIn profile
 */
export class LinkedInProfile {
    "id": number;
    "email": string;
    "password": string;
    "phoneNumber": string;
    "positions": string[];
    "locations": string[];
    "remoteOnly": boolean;
    "profileUrl": string;
    "yearsExperience": number;
    "userCity": string;
    "userState": string;
    "zipCode": string;
    "desiredSalary": number;
    "blacklist": string[];
    "blacklistTitles": string[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new LinkedInProfile instance. */
    constructor($$source: Partial<LinkedInProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("phoneNumber" in $$source)) {
            this["phoneNumber"] = "";
        }
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("remoteOnly" in $$source)) {
            this["remoteOnly"] = false;
        }
        if (!("profileUrl" in $$source)) {
            this["profileUrl"] = "";
        }
        if (!("yearsExperience" in $$source)) {
            this["yearsExperience"] = 0;
        }
        if (!("userCity" in $$source)) {
            this["userCity"] = "";
        }
        if (!("userState" in $$source)) {
            this["userState"] = "";
        }
        if (!("zipCode" in $$source)) {
            this["zipCode"] = "";
        }
        if (!("desiredSalary" in $$source)) {
            this["desiredSalary"] = 0;
        }
        if (!("blacklist" in $$source)) {
            this["blacklist"] = [];
        }
        if (!("blacklistTitles" in $$source)) {
            this["blacklistTitles"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedInProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkedInProfile {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField4_0($$parsedSource["positions"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField5_0($$parsedSource["locations"]);
        }
        if ("blacklist" in $$parsedSource) {
            $$parsedSource["blacklist"] = $$createField13_0($$parsedSource["blacklist"]);
        }
        if ("blacklistTitles" in $$parsedSource) {
            $$parsedSource["blacklistTitles"] = $$createField14_0($$parsedSource["blacklistTitles"]);
        }
        return new LinkedInProfile($$parsedSource as Partial<LinkedInProfile>);
    }
}

/**
 * LinkedInProfileUpdate contains fields that can be updated on a profile
 */
export class LinkedInProfileUpdate {
    "email": string;
    "password": string;
    "phoneNumber": string;
    "positions": string[];
    "locations": string[];
    "remoteOnly": boolean;
    "profileUrl": string;
    "yearsExperience": number;
    "userCity": string;
    "userState": string;
    "zipCode": string;
    "desiredSalary": number;
    "blacklist": string[];
    "blacklistTitles": string[];

    /** Creates a new LinkedInProfileUpdate instance. */
    constructor($$source: Partial<LinkedInProfileUpdate> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("phoneNumber" in $$source)) {
            this["phoneNumber"] = "";
        }
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("remoteOnly" in $$source)) {
            this["remoteOnly"] = false;
        }
        if (!("profileUrl" in $$source)) {
            this["profileUrl"] = "";
        }
        if (!("yearsExperience" in $$source)) {
            this["yearsExperience"] = 0;
        }
        if (!("userCity" in $$source)) {
            this["userCity"] = "";
        }
        if (!("userState" in $$source)) {
            this["userState"] = "";
        }
        if (!("zipCode" in $$source)) {
            this["zipCode"] = "";
        }
        if (!("desiredSalary" in $$source)) {
            this["desiredSalary"] = 0;
        }
        if (!("blacklist" in $$source)) {
            this["blacklist"] = [];
        }
        if (!("blacklistTitles" in $$source)) {
            this["blacklistTitles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedInProfileUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkedInProfileUpdate {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField3_0($$parsedSource["positions"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField4_0($$parsedSource["locations"]);
        }
        if ("blacklist" in $$parsedSource) {
            $$parsedSource["blacklist"] = $$createField12_0($$parsedSource["blacklist"]);
        }
        if ("blacklistTitles" in $$parsedSource) {
            $$parsedSource["blacklistTitles"] = $$createField13_0($$parsedSource["blacklistTitles"]);
        }
        return new LinkedInProfileUpdate($$parsedSource as Partial<LinkedInProfileUpdate>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
